### ISSUE TITLE
The site is down, probably because heroku free tier ended??

### ISSUE THREAD

**Issue by planyway** [suvnshr/developer-search#43]

**Comment by suvnshr** [comment]
Yes, looking for options to migrate it.


you have some suggestions as to where I can transfer it?

**Comment by suvnshr** [comment]
Thanks for informing me.

It is live again: https://devxplore.onrender.com/?q=javascript

Thanks

**Comment by planyway** [comment]
Thanks a lot. Yeah, onrender is the only choice I guess.
